version: '3.8'

services:
  sommerhus-vote:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - voting_data:/app/data
    environment:
      - NODE_ENV=production
    restart: unless-stopped

volumes:
  voting_data:
